### ISSUE TITLE
[BUG] Connection Reset

### ISSUE THREAD

**Issue by Puntoboy** [bcleonard/proxmox-qdevice#10]
**Describe the bug**
I eventually got the networking setup so the container connects to my network directly. but now I can't ssh to it, and this adding it to the cluster doesn't work. 

I just get "Connection reset by 192.168.1.110 port 22"

Running in verbose mode I get this:

PS C:\Users\chris> ssh -v root@192.168.1.110
OpenSSH_for_Windows_8.6p1, LibreSSL 3.4.3
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug1: Connecting to 192.168.1.110 [192.168.1.110] port 22.
debug1: Connection established.
debug1: identity file C:\\Users\\chris/.ssh/id_rsa type 0
debug1: identity file C:\\Users\\chris/.ssh/id_rsa-cert type -1
debug1: identity file C:\\Users\\chris/.ssh/id_dsa type -1
debug1: identity file C:\\Users\\chris/.ssh/id_dsa-cert type -1
debug1: identity file C:\\Users\\chris/.ssh/id_ecdsa type -1
debug1: identity file C:\\Users\\chris/.ssh/id_ecdsa-cert type -1
debug1: identity file C:\\Users\\chris/.ssh/id_ecdsa_sk type -1
debug1: identity file C:\\Users\\chris/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file C:\\Users\\chris/.ssh/id_ed25519 type -1
debug1: identity file C:\\Users\\chris/.ssh/id_ed25519-cert type -1
debug1: identity file C:\\Users\\chris/.ssh/id_ed25519_sk type -1
debug1: identity file C:\\Users\\chris/.ssh/id_ed25519_sk-cert type -1
debug1: identity file C:\\Users\\chris/.ssh/id_xmss type -1
debug1: identity file C:\\Users\\chris/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_for_Windows_8.6
debug1: Remote protocol version 2.0, remote software version OpenSSH_9.2p1 Debian-2
debug1: compat_banner: match: OpenSSH_9.2p1 Debian-2 pat OpenSSH* compat 0x04000000
debug1: Authenticating to 192.168.1.110:22 as 'root'
debug1: load_hostkeys: fopen C:\\Users\\chris/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen __PROGRAMDATA__\\ssh/ssh_known_hosts2: No such file or directory
debug1: SSH2_MSG_KEXINIT sent
Connection reset by 192.168.1.110 port 22

I use SSH on my PC every day so not sure why this is failing.

**To Reproduce**
my compose yaml

services:
  qnetd:
    container_name: proxmox-qdevice
    image: bcleonard/proxmox-qdevice
    build: .
    ports:
      - "22:22"
      - "5403:5403"
    environment:
      - "NEW_ROOT_PASSWORD=password"
    volumes:
      - /run/sshd
      - /volume1/docker/corosync:/etc/corosync
    restart: unless-stopped
    hostname: pve-qdevice
    networks: 
      vlan:
        ipv4_address: 192.168.1.110

networks:
 vlan:
    driver: macvlan
    driver_opts:
      parent: ovs_bond0
    ipam:
       driver: default
       config:
        - subnet: "192.168.1.0/24"
          ip_range: "192.168.1.110/32"
          gateway: "192.168.1.254"

**Expected behavior**
ssh to connect. Corosync to join cluster

**host server (please complete the following information):**
 - OS: Synology NAS
 - architecture x86
 - Version DSM 7.1.1-42962 Update 6

**Comment by bcleonard** [comment]
This container was never tested on synology.  

Based on other reports, synology utilizes an older kernel which is incompatible with the Debian 12 which is what the container is built on.

See #2
