### ISSUE TITLE
Error response from daemon: Address already in use

### ISSUE THREAD

**Issue by nevusZ** [bcleonard/proxmox-qdevice#11]
hy, 
i changed volume path on my docker-compose.yaml file
after restart of the container i get

"Error response from daemon: Address already in use"

that is strange because that container uses an extra ip 
after changing it to +1 in last octet, the container is running. but then i have to setup the qdevice again.

what can i do, to make the container run again with original ip?

for info, i needed to adjust the docker file for debian-bullseye-slim because of synology docker host

thanks

`services:
  qnetd:
    container_name: proxmox-qdevice
    #image: bcleonard/proxmox-qdevice
    image: syno-pve-qdevice/proxmox-qdevice
    build: .
    ports:
      - "22:22"
      - "5403:5403"
    environment:
      - "NEW_ROOT_PASSWORD=secret"
    volumes:
      - /run/sshd
      - ./data:/etc/corosync
    restart: unless-stopped
    hostname: pve-qdevice
    networks:
      vlan:
        ipv4_address: 192.168.11.47

networks:
 vlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
       driver: default
       config:
        - subnet: "192.168.11.47/24"
          ip_range: "192.168.11.47/32"
`

**Comment by bcleonard** [comment]
As i wrote that last comment, it occurred to me that you there are at least two other ways to get an external qnetd process on port 22 without using a 2nd IP address.  I don't know anything about synology, so i don't know if either works, but these alternatives should work on UNIX like OS.

1.  change the port of SSHD running on your OS host from 22 to something else.   I'm not gonna lie, this is extreme.  Depending on what is running on your OS this maybe simple or it may not.   That's gonna be dependent on your running environment.
2. install a small virtual image and running the first alternative option there.   This means you wouldn't have to change port 22 on your OS host, but it does mean you need have a 2nd IP address and assign it to the new virtual image.   I mean small virtual image in that I run my qnetd-device container on a Debian instance with 1 GB Mem, 1 CPU & 10 GB of disk space.  I run this virtual image on my TrueNAS Scale server which is on a separate physical device that my proxmox cluster.

Again I'm not sure how practical or easy these are to run.  It was just alternatives that occurred to me.

your mileage may vary.

**Comment by nevusZ** [comment]
hy, 
i changed ip in the docker-compose.yaml to +1 higher
container starts without error

assigning the new qdevice is simple as 
pvecm qdevice remove
pvecm qdevice setup newip -f

i don't understand why it could not be started with old ip.
doesn't matter, it works now
thanks and sorry

**Comment by bcleonard** [comment]
No worries.  Glad you got it figured out.
