### ISSUE TITLE
Can we use a bridged network ?

### ISSUE THREAD

**Issue by nakedgoat** [bcleonard/proxmox-qdevice#13]
here is a snippet from mine but it doesn't working (error posted at end).
    restart: unless-stopped
    hostname: qdevice
    networks:
      - bridge_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5403/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bridge_net:
    driver: bridge

docker-compose logs -f qnetd
Attaching to proxmox-qdevice
proxmox-qdevice | /usr/lib/python3/dist-packages/supervisor/options.py:474: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
proxmox-qdevice |   self.warnings.warn(
proxmox-qdevice | 2024-10-27 20:13:16,442 INFO Set uid to user 0 succeeded
proxmox-qdevice | 2024-10-27 20:13:16,454 INFO supervisord started with pid 1
proxmox-qdevice | 2024-10-27 20:13:17,464 INFO spawned: 'set_root_password' with pid 7
proxmox-qdevice | 2024-10-27 20:13:17,475 INFO spawned: 'corosync-qnetd' with pid 8
proxmox-qdevice | 2024-10-27 20:13:17,486 INFO spawned: 'sshd' with pid 9
proxmox-qdevice | 2024-10-27 20:13:17,492 INFO success: set_root_password entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
proxmox-qdevice | 2024-10-27 20:13:17,514 WARN exited: corosync-qnetd (exit status 1; not expected)
proxmox-qdevice | 2024-10-27 20:13:17,627 INFO exited: set_root_password (exit status 0; expected)
proxmox-qdevice | 2024-10-27 20:13:18,637 INFO spawned: 'corosync-qnetd' with pid 14
proxmox-qdevice | 2024-10-27 20:13:18,639 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
proxmox-qdevice | 2024-10-27 20:13:18,660 WARN exited: corosync-qnetd (exit status 1; not expected)
proxmox-qdevice | 2024-10-27 20:13:20,672 INFO spawned: 'corosync-qnetd' with pid 15
proxmox-qdevice | 2024-10-27 20:13:20,698 WARN exited: corosync-qnetd (exit status 1; not expected)
proxmox-qdevice | 2024-10-27 20:13:23,746 INFO spawned: 'corosync-qnetd' with pid 16
proxmox-qdevice | 2024-10-27 20:13:23,782 WARN exited: corosync-qnetd (exit status 1; not expected)
proxmox-qdevice | 2024-10-27 20:13:24,786 INFO gave up: corosync-qnetd entered FATAL state, too many start retries too quickly
proxmox-qdevice exited with code 137

**Comment by bcleonard** [comment]
If you don't have any other applications running on port 22, then it *might* work on a bridge network.   

I had an application already running on port 22, namely sshd on the virtual instance itself.   I needed to run both the sshd on the virtual image and sshd with the docker instance.

This won't work with a bridge network.
